[package]
name = "odata-edm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemafy = "0.6"
yaserde = "0.8"
yaserde_derive = "0.8"
reqwest = "0.11"
async-trait = "0.1"
log = "0.4"